#!/usr/bin/env bash

set -e

function print_version(){
    echo "Kubernetes for ARM v1.1"
    exit 1
}

function print_help() {
    echo "Usage: $0"
    echo "    -h            Print this help"
    echo "    -v            Print version info"
    echo "    -l            List available versions"
    echo "    -i [version]  Specify docker version to install"
    echo
    echo "You may specify a docker version. See:"
    echo "https://github.com/ulm0/k8s-arm#installing-a-given-version"
    exit 1
}

function docker_versions(){
    info "Docker" "List of available versions:"
    echo "  - 18.03.1             | Might work"
    echo "  - 18.03.0             | Might work"
    echo "  - 17.12.1             | Works"
    echo "  - 17.12.0             | Works"
    echo "  - 17.09.1             | Works"
    echo "  - 17.09.0             | Works"
    echo "  - 17.06.2             | Works"
    echo "  - 17.06.1             | Works"
    echo "  - 17.06.0             | Works"
    echo "  - 17.03.2  (Default)  | Recommended"
    echo "  - 17.03.1             | Recommended"
    echo "  - 17.03.0             | Recommended"
    exit 1
}

# Display an error message and quit
function bail() {
    FG="1;31m"
    BG="40m"
    echo -en "[\033[${FG}\033[${BG}Error\033[0m]"
    echo "$*"
    exit 1
}

# Display an info message
function info() {
    task="$1"
    shift
    FG="1;32m"
    BG="40m"
    echo -e "[\033[${FG}\033[${BG}${task}\033[0m] $*"
}

# Refresh repos
function update(){
    info "Info" "Updating repos..."
    apt-get -qq update
}


# Install dependencies according to 
# https://docs.docker.com/install/linux/docker-ce/ubuntu/
function deps(){
    info "Info" "Installing dependencies..."
    apt-get install -qq -y apt-transport-https ca-certificates curl lsb-release software-properties-common
}

# Get GPG Keys
function get_keys(){
    info "Keys" "Getting key for ${1}"
    curl -fsSL "${1}" | apt-key add -
}

# Add a given repo
function add_repo(){
    info "Repo" "Adding to ${1}"
    echo "${2}" | tee "${1}"
}

function set_storage_driver(){
    info "Docker" "Configuring storage driver..."
    echo {\"storage-driver\":\"overlay2\"} > /etc/docker/daemon.json
    systemctl daemon-reload
    systemctl restart docker
}

# Install Docker
function install_docker(){
    if [[ -s $(which docker) ]]; then
        info "Docker" "Previous installation found..."
        remove_prev_docker
    fi
    get_keys "https://download.docker.com/linux/$(lsb_release -is | tr A-Z a-z)/gpg"
    add_repo "/etc/apt/sources.list.d/docker.list" "deb [arch=armhf] https://download.docker.com/linux/$(lsb_release -is | tr A-Z a-z) $(lsb_release -cs) stable"
    update
    info "Docker" "Installing..."
    # apt-get install -qq -y docker-ce=${1}~ce-0~$(lsb_release -is | tr A-Z a-z)
    apt-get install -qq -y docker-ce=$(apt-cache madison docker-ce | grep ${1} | head -1 | awk '{print $3}')
    info "Docker" "Setting on hold..."
    apt-mark -qq hold docker-ce
    set_storage_driver
}

# Look for previous docker installation and remove it
function remove_prev_docker(){
    info "Docker" "Removing existing installation..."
    apt-get -qq -y remove docker docker-ce docker.io docker-engine
    apt-get -qq -y autoremove docker docker-ce docker.io docker-engine
    apt-get -qq -y purge docker docker-ce docker.io docker-engine
    if [[ -s /etc/apt/sources.list.d/docker.list ]]; then
        info "Docker" "Removing old source repo..."
        rm -f /etc/apt/sources.list.d/docker.list
    fi
}

# Install K8s
function install_kubernetes(){
    get_keys "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    add_repo "/etc/apt/sources.list.d/kubernetes.list" "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    update
    info "Kubernetes" "Installing..."
    apt-get install -qq -y kubelet kubeadm kubectl
}

if [[ $EUID -ne 0 ]]; then
    bail "must be run as root. try: sudo ${0}"
fi

# Handle arguments:
args=$(getopt -uo 'hvli:' -- $*)
[ $? != 0 ] && print_help
set -- $args

for i
do
    case "$i"
    in
        -h)
            print_help
            ;;
        -v)
            print_version
            ;;
        -l)
            docker_versions
            ;;
        -i)
            docker_version="$2"
            shift
            shift
            ;;
    esac
done

info "Start" "This tool will remove any docker installed on the system"
if [[ -z "$docker_version" ]]; then
    info "Start" "and install a suitable docker version for kubernetes"
else
    info "Start" "and install the chosen docker version for kubernetes"
fi
read -p "Really proceed? (y)es / (n)o " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Quitting."
    exit
fi

if [[ -z "$docker_version" ]]; then
    docker_version="17.03"
    info "Info" "No docker version specified, installing default (${docker_version})"
fi

update
deps
install_docker "${docker_version}"
install_kubernetes
info "Info" "Docker and Kubernetes have been installed"
info "Info" "You might want to check:"
info "Info" "docker version"
info "Info" "kubectl version"
info "Info" "kubeadm version"
info "Info" "kubelet version"
info "Info" "Enjoy...!"